#!/usr/bin/env ruby

unless File.exist?('./Rakefile') || File.exist?('./Gemfile')
  abort 'Please run annotate from the root of the project.'
end
require 'awesome_annotate'

AwesomeAnnotate::CLI.start ARGV
